#Requires -Version 5.1
<#
.SYNOPSIS
Removes all ConfigMgr device affinities for a specified user.

.DESCRIPTION
Imports the Configuration Manager module, connects to the specified site, retrieves
all device affinities for the target user, and removes them using
Remove-CMDeviceAffinityFromUser. Supports -WhatIf for safe simulation.

.PARAMETER UserName
The domain user (sAMAccountName or UPN) whose device affinities will be removed.

.PARAMETER SiteCode
The three-character site code for the Configuration Manager site.

.PARAMETER SiteServer
The primary site server to connect to. Defaults to the local computer name.

.PARAMETER WhatIf
Simulate the removal actions without making changes.

.EXAMPLE
PS> .\Remove-AllDeviceAffinityForUser.ps1 -UserName "contoso\\jdoe" -SiteCode PRI -SiteServer cm01

.EXAMPLE
PS> .\Remove-AllDeviceAffinityForUser.ps1 -UserName "jdoe@contoso.com" -SiteCode PRI -WhatIf

.NOTES
Author: Autogenerated by ChatGPT
#>

param (
[Parameter(Mandatory = $true)]
[string]$UserName,

[Parameter(Mandatory = $true)]
[ValidatePattern("^[A-Za-z0-9]{3}$")]
[string]$SiteCode,

[Parameter()]
[string]$SiteServer = $env:COMPUTERNAME,

[switch]$WhatIf
)

function Import-CMModule {
if (Get-Module -Name ConfigurationManager) {
    return
}

$configMgrPath = Join-Path -Path $env:SMS_ADMIN_UI_PATH -ChildPath "..\ConfigurationManager.psd1"
if (-not (Test-Path -Path $configMgrPath)) {
    throw "ConfigurationManager.psd1 not found. Verify the ConfigMgr console is installed."
}

Import-Module -Name $configMgrPath -ErrorAction Stop
}

function Set-CMSiteLocation {
param(
    [Parameter(Mandatory = $true)]
    [string]$Code,

    [Parameter(Mandatory = $true)]
    [string]$Server
)

$cmsProvider = Get-PSDrive -PSProvider CMSite -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -eq $Code }

if (-not $cmsProvider) {
    New-PSDrive -Name $Code -PSProvider CMSite -Root $Server | Out-Null
}

Set-Location -Path "$Code:" -ErrorAction Stop
}

$startingLocation = Get-Location
try {
Write-Host "Importing Configuration Manager module..." -ForegroundColor Cyan
Import-CMModule

Write-Host "Connecting to site $SiteCode on server $SiteServer..." -ForegroundColor Cyan
Set-CMSiteLocation -Code $SiteCode -Server $SiteServer

Write-Host "Retrieving device affinities for user '$UserName'..." -ForegroundColor Cyan
$affinities = Get-CMUserDeviceAffinity -UserName $UserName -ErrorAction Stop

if (-not $affinities) {
    Write-Host "No device affinities found for $UserName." -ForegroundColor Yellow
    return
}

foreach ($affinity in $affinities) {
    $deviceName = $affinity.MachineName
    if (-not $deviceName) {
        continue
    }

    if ($WhatIf) {
        Write-Host "[WhatIf] Would remove affinity for device '$deviceName'." -ForegroundColor Yellow
        continue
    }

    Write-Host "Removing affinity for device '$deviceName'..." -ForegroundColor Green
    Remove-CMDeviceAffinityFromUser -UserName $UserName -DeviceName $deviceName -Confirm:$false
}

if (-not $WhatIf) {
    Write-Host "Completed removing device affinities for $UserName." -ForegroundColor Green
} else {
    Write-Host "WhatIf run completed. No changes were made." -ForegroundColor Yellow
}
}
catch {
Write-Error $_.Exception.Message
}
finally {
Set-Location -Path $startingLocation
}
